// Himalayan Routes Master Database

export const DISTRICTS = [
  { id: 'kangra', name: 'Kangra', hq: 'Dharamshala', majorStands: ['Dharamshala ISBT', 'Palampur', 'Kangra', 'Baijnath', 'Nurpur'], desc: 'Largest district by population, home to Dhauladhar ranges, tea gardens & major transport hubs.' },
  { id: 'shimla', name: 'Shimla', hq: 'Shimla', majorStands: ['Shimla ISBT (Tutikandi)', 'Rampur', 'Rohru', 'Theog', 'Chopal'], desc: 'State capital, hub for inter-state Volvo services, high altitude rural services.' },
  { id: 'mandi', name: 'Mandi', hq: 'Mandi', majorStands: ['Mandi ISBT', 'Sunder Nagar', 'Sarkaghat', 'Joginder Nagar'], desc: 'Central connection district connecting Shimla, Kullu, Kangra & Bilaspur.' },
  { id: 'kullu', name: 'Kullu', hq: 'Kullu', majorStands: ['Kullu ISBT', 'Manali ISBT', 'Bhuntar', 'Anni'], desc: 'Gateway to Solang, Rohtang, Lahaul & major tourist Volvo corridors.' },
  { id: 'chamba', name: 'Chamba', hq: 'Chamba', majorStands: ['Chamba ISBT', 'Dalhousie', 'Bharmour', 'Chowari'], desc: 'Picturesque alpine region with steep terrain routes connecting Pathankot & Punjab.' },
  { id: 'hamirpur', name: 'Hamirpur', hq: 'Hamirpur', majorStands: ['Hamirpur ISBT', 'Nadaun', 'Barsar', 'Sujanpur'], desc: 'High density bus network district connecting educational & regional hubs.' },
  { id: 'una', name: 'Una', hq: 'Una', majorStands: ['Una ISBT', 'Amb', 'Bangana', 'Gagret'], desc: 'Border district connecting Himachal rail network & major plain routes.' },
  { id: 'bilaspur', name: 'Bilaspur', hq: 'Bilaspur', majorStands: ['Bilaspur Bus Stand', 'Ghumarwin', 'Swarghat'], desc: 'Gateway district on Chandigarh-Manali NH with Gobind Sagar lake.' },
  { id: 'solan', name: 'Solan', hq: 'Solan', majorStands: ['Solan Bus Stand', 'Baddi ISBT', 'Nalagarh', 'Kasauli'], desc: 'Industrial and educational hub bordering Chandigarh & Haryana.' },
  { id: 'sirmaur', name: 'Sirmaur', hq: 'Nahan', majorStands: ['Nahan Bus Stand', 'Paonta Sahib', 'Rajgarh'], desc: 'Southernmost district with pilgrimage routes to Paonta Sahib.' },
  { id: 'kinnaur', name: 'Kinnaur', hq: 'Reckong Peo', majorStands: ['Reckong Peo', 'Kalpa', 'Pooh', 'Sangla'], desc: 'Tribal high-altitude mountain region serviced by rugged HRTC All-Terrain buses.' },
  { id: 'lahaul-spiti', name: 'Lahaul & Spiti', hq: 'Keylong', majorStands: ['Keylong', 'Kaza', 'Udaipur', 'Tabo'], desc: 'Trans-Himalayan desert & valley region accessed via Atal Tunnel.' }
];

export const BUS_STANDS = [
  { id: 'bs-palampur', name: 'Palampur Bus Stand', district: 'Kangra', location: 'Main Chowk, Palampur', hrtcDepot: true, contact: '01894-230250', majorDestinations: ['Chandigarh', 'Delhi', 'Pathankot', 'Dharamshala', 'Shimla', 'Baijnath'] },
  { id: 'bs-dharamshala', name: 'Dharamshala ISBT', district: 'Kangra', location: 'Lower Dharamshala', hrtcDepot: true, contact: '01892-224903', majorDestinations: ['Delhi', 'Chandigarh', 'Shimla', 'Manali', 'Pathankot', 'McLeod Ganj'] },
  { id: 'bs-shimla', name: 'Shimla ISBT (Tutikandi)', district: 'Shimla', location: 'Tutikandi, Shimla', hrtcDepot: true, contact: '0177-2656326', majorDestinations: ['Delhi', 'Chandigarh', 'Manali', 'Dharamshala', 'Rampur', 'Rohru', 'Hardwar'] },
  { id: 'bs-manali', name: 'Manali Bus Stand', district: 'Kullu', location: 'Mall Road / Private Volvo Stand', hrtcDepot: true, contact: '01902-252323', majorDestinations: ['Delhi', 'Chandigarh', 'Shimla', 'Dharamshala', 'Keylong', 'Leh'] },
  { id: 'bs-mandi', name: 'Mandi ISBT', district: 'Mandi', location: 'Near Seri Bazar, Mandi', hrtcDepot: true, contact: '01905-235300', majorDestinations: ['Delhi', 'Shimla', 'Manali', 'Pathankot', 'Kullu', 'Sarkaghat'] },
  { id: 'bs-kangra', name: 'Kangra Bus Stand', district: 'Kangra', location: 'Near Temple Road', hrtcDepot: true, contact: '01892-265114', majorDestinations: ['Pathankot', 'Chandigarh', 'Dharamshala', 'Hoshiarpur', 'Jwalamukhi'] },
  { id: 'bs-pathankot', name: 'Pathankot Maharana Pratap ISBT', district: 'Inter-State Border (Punjab)', location: 'Pathankot', hrtcDepot: false, contact: '0186-2220033', majorDestinations: ['Palampur', 'Dharamshala', 'Dalhousie', 'Chamba', 'Jammu', 'Amritsar'] },
  { id: 'bs-baijnath', name: 'Baijnath Bus Stand', district: 'Kangra', location: 'Near Temple', hrtcDepot: true, contact: '01894-263028', majorDestinations: ['Shimla', 'Chandigarh', 'Delhi', 'Pathankot', 'Joginder Nagar'] },
  { id: 'bs-hamirpur', name: 'Hamirpur ISBT', district: 'Hamirpur', location: 'Main Highway', hrtcDepot: true, contact: '01972-222284', majorDestinations: ['Shimla', 'Chandigarh', 'Delhi', 'Dharamshala', 'Jwalaji'] },
  { id: 'bs-chamba', name: 'Chamba ISBT', district: 'Chamba', location: 'Chamba Town', hrtcDepot: true, contact: '01899-222286', majorDestinations: ['Pathankot', 'Shimla', 'Bharmour', 'Dalhousie', 'Delhi'] }
];

export const OPERATORS = [
  {
    id: 'hrtc',
    name: 'HRTC (Himachal Road Transport Corp)',
    type: 'Government',
    headquarters: 'Shimla, Himachal Pradesh',
    district: 'Shimla',
    contact: '0177-2657326 / Toll Free 1800-180-8185',
    website: 'https://hrtchp.com',
    social_links: { facebook: 'https://facebook.com/hrtchpofficial', twitter: '@HRTC_HP' },
    verification_status: '✓ Verified',
    depots: ['Shimla', 'Dharamshala', 'Palampur', 'Baijnath', 'Kangra', 'Mandi', 'Kullu', 'Manali', 'Hamirpur', 'Una', 'Bilaspur', 'Solan', 'Nahan', 'Reckong Peo', 'Rampur', 'Rohru', 'Chamba', 'Dalhousie'],
    logo: '🏔️',
    description: 'State government transport undertaking operating over 3,100 ordinary, electric, AC deluxe, and luxury Volvo/Himsuta buses across HP and neighboring states.'
  },
  {
    id: 'rana-coach',
    name: 'Rana Coach',
    type: 'Private Operator',
    headquarters: 'Palampur, Kangra District',
    district: 'Kangra',
    contact: '+91 98160-45120',
    website: 'N/A',
    verification_status: '✓ Verified',
    logo: '🚌',
    description: 'Premier private operator providing dependable ordinary and semi-deluxe services along the Kangra valley belt (Palampur, Nagrota, Pathankot, Jwalaji).'
  },
  {
    id: 'new-walia',
    name: 'New Walia Bus Service',
    type: 'Private Operator',
    headquarters: 'Dharamshala, Kangra District',
    district: 'Kangra',
    contact: '+91 94180-22340',
    verification_status: '✓ Verified',
    logo: '🚍',
    description: 'Operates comfortable daily regional services between Dharamshala, Pathankot, Hoshiarpur, and local sub-routes.'
  },
  {
    id: 'lucky-bus',
    name: 'Lucky Bus Service',
    type: 'Private Operator',
    headquarters: 'Mandi, Himachal Pradesh',
    district: 'Mandi',
    contact: '+91 98171-88900',
    verification_status: '✓ Verified',
    logo: '🚐',
    description: 'Specializes in local Mandi-Kullu-Sarkaghat rural connectivity routes with regular frequency.'
  },
  {
    id: 'kajal-bus',
    name: 'Kajal Bus Service',
    type: 'Private Operator',
    headquarters: 'Kangra, Himachal Pradesh',
    district: 'Kangra',
    contact: '+91 98055-12111',
    verification_status: '✓ Verified',
    logo: '🚌',
    description: 'Reliable private bus operator running Kangra to Dehra, Chintpurni, and Hoshiarpur inter-state routes.'
  },
  {
    id: 'shivam-deluxe',
    name: 'Shivam Luxury Travel',
    type: 'Private Operator',
    headquarters: 'Manali, Kullu District',
    district: 'Kullu',
    contact: '+91 98162-99001',
    verification_status: '✓ Verified',
    logo: '⭐',
    description: 'Private luxury sleeper and AC Volvo operator running overnight services on Manali-Delhi and Dharamshala-Delhi routes.'
  }
];

export const BUS_TYPES = [
  'HRTC Ordinary',
  'HRTC Electric',
  'HRTC Volvo / Himsuta',
  'HRTC AC Deluxe',
  'Private Ordinary',
  'Private Luxury Bus',
  'Private AC Volvo',
  'Local Village Bus'
];

export const ROUTES = [
  // --- HRTC VOLVO / HIMSUTA ---
  {
    id: 'route-volvo-1',
    operator_id: 'hrtc',
    operator_name: 'HRTC Himsuta Volvo',
    service_number: 'HP-VOLVO-101',
    origin: 'Dharamshala',
    destination: 'Delhi ISBT Kashmiri Gate',
    route_category: 'HRTC Volvo / Himsuta',
    bus_type: 'HRTC Volvo / Himsuta',
    is_volvo: true,
    is_ac: true,
    is_hrtc: true,
    is_local: false,
    departure_time: '20:30',
    arrival_time: '06:00 (Next Day)',
    operating_days: 'Daily',
    frequency: '1 service/day',
    daily_frequency_count: 1,
    fare: '₹1,350',
    depot: 'Dharamshala',
    district: 'Kangra',
    stops: [
      { name: 'Dharamshala ISBT', dep: '20:30' },
      { name: 'Kangra Bypass', dep: '21:05' },
      { name: 'Ranital', dep: '21:40' },
      { name: 'Dehra Gopipur', dep: '22:15' },
      { name: 'Amb', dep: '23:00' },
      { name: 'Una ISBT', dep: '23:45' },
      { name: 'Chandigarh ISBT 43', dep: '02:15' },
      { name: 'Delhi ISBT Kashmiri Gate', arr: '06:00' }
    ],
    source: 'Official HRTC Portal',
    source_url: 'https://hrtchp.com/volvo-schedule',
    last_verified: '2026-09-18',
    verification_status: '✓ Verified'
  },
  {
    id: 'route-volvo-2',
    operator_id: 'hrtc',
    operator_name: 'HRTC Himsuta Volvo',
    service_number: 'HP-VOLVO-104',
    origin: 'Palampur',
    destination: 'Delhi ISBT Kashmiri Gate',
    route_category: 'HRTC Volvo / Himsuta',
    bus_type: 'HRTC Volvo / Himsuta',
    is_volvo: true,
    is_ac: true,
    is_hrtc: true,
    is_local: false,
    departure_time: '19:45',
    arrival_time: '05:30 (Next Day)',
    operating_days: 'Daily',
    frequency: '1 service/day',
    daily_frequency_count: 1,
    fare: '₹1,320',
    depot: 'Palampur',
    district: 'Kangra',
    stops: [
      { name: 'Palampur Bus Stand', dep: '19:45' },
      { name: 'Maranda', dep: '19:55' },
      { name: 'Bhawarna', dep: '20:10' },
      { name: 'Nagrota Bagwan', dep: '20:30' },
      { name: 'Kangra', dep: '21:00' },
      { name: 'Una ISBT', dep: '23:15' },
      { name: 'Chandigarh ISBT 43', dep: '01:30' },
      { name: 'Delhi ISBT Kashmiri Gate', arr: '05:30' }
    ],
    source: 'Official HRTC Online Booking',
    source_url: 'https://hrtchp.com',
    last_verified: '2026-09-19',
    verification_status: '✓ Verified'
  },
  {
    id: 'route-volvo-3',
    operator_id: 'hrtc',
    operator_name: 'HRTC Himsuta Volvo',
    service_number: 'HP-VOLVO-208',
    origin: 'Manali',
    destination: 'Delhi ISBT Kashmiri Gate',
    route_category: 'HRTC Volvo / Himsuta',
    bus_type: 'HRTC Volvo / Himsuta',
    is_volvo: true,
    is_ac: true,
    is_hrtc: true,
    is_local: false,
    departure_time: '18:00',
    arrival_time: '07:15 (Next Day)',
    operating_days: 'Daily',
    frequency: '3 services/day',
    daily_frequency_count: 3,
    fare: '₹1,480',
    depot: 'Manali',
    district: 'Kullu',
    stops: [
      { name: 'Manali Bus Stand', dep: '18:00' },
      { name: 'Kullu ISBT', dep: '19:15' },
      { name: 'Aut Tunnel', dep: '20:00' },
      { name: 'Mandi ISBT', dep: '21:15' },
      { name: 'Sunder Nagar', dep: '22:00' },
      { name: 'Bilaspur', dep: '23:30' },
      { name: 'Chandigarh ISBT 43', dep: '02:30' },
      { name: 'Delhi ISBT Kashmiri Gate', arr: '07:15' }
    ],
    source: 'Official HRTC Timetable',
    source_url: 'https://hrtchp.com',
    last_verified: '2026-09-17',
    verification_status: '✓ Verified'
  },
  {
    id: 'route-volvo-4',
    operator_id: 'hrtc',
    operator_name: 'HRTC Himsuta Volvo',
    service_number: 'HP-VOLVO-302',
    origin: 'Shimla',
    destination: 'Delhi ISBT Kashmiri Gate',
    route_category: 'HRTC Volvo / Himsuta',
    bus_type: 'HRTC Volvo / Himsuta',
    is_volvo: true,
    is_ac: true,
    is_hrtc: true,
    is_local: false,
    departure_time: '21:15',
    arrival_time: '06:00 (Next Day)',
    operating_days: 'Daily',
    frequency: '5 services/day',
    daily_frequency_count: 5,
    fare: '₹1,150',
    depot: 'Shimla',
    district: 'Shimla',
    stops: [
      { name: 'Shimla ISBT (Tutikandi)', dep: '21:15' },
      { name: 'Solan Bus Stand', dep: '22:45' },
      { name: 'Dharampur', dep: '23:15' },
      { name: 'Parwanoo', dep: '23:55' },
      { name: 'Chandigarh ISBT 43', dep: '01:15' },
      { name: 'Delhi ISBT Kashmiri Gate', arr: '06:00' }
    ],
    source: 'Official HRTC Ticketing',
    source_url: 'https://hrtchp.com',
    last_verified: '2026-09-19',
    verification_status: '✓ Verified'
  },

  // --- HRTC ORDINARY & ELECTRIC ---
  {
    id: 'route-ord-1',
    operator_id: 'hrtc',
    operator_name: 'HRTC Ordinary',
    service_number: 'HP-ORD-412',
    origin: 'Palampur',
    destination: 'Chandigarh ISBT 43',
    route_category: 'Ordinary Buses',
    bus_type: 'HRTC Ordinary',
    is_volvo: false,
    is_ac: false,
    is_hrtc: true,
    is_local: false,
    departure_time: '05:30',
    arrival_time: '11:45',
    operating_days: 'Daily',
    frequency: 'Hourly',
    daily_frequency_count: 8,
    fare: '₹340',
    depot: 'Palampur',
    district: 'Kangra',
    stops: [
      { name: 'Palampur Bus Stand', dep: '05:30' },
      { name: 'Bhawarna', dep: '05:55' },
      { name: 'Nagrota Bagwan', dep: '06:20' },
      { name: 'Kangra ISBT', dep: '06:50' },
      { name: 'Ranital', dep: '07:25' },
      { name: 'Dehra', dep: '08:00' },
      { name: 'Amb', dep: '08:45' },
      { name: 'Una ISBT', dep: '09:30' },
      { name: 'Nangal', dep: '10:05' },
      { name: 'Ropar', dep: '10:55' },
      { name: 'Chandigarh ISBT 43', arr: '11:45' }
    ],
    source: 'Palampur Depot Timeboard',
    source_url: 'Official Depot Notice',
    last_verified: '2026-09-15',
    verification_status: '✓ Verified'
  },
  {
    id: 'route-elec-1',
    operator_id: 'hrtc',
    operator_name: 'HRTC Electric Service',
    service_number: 'HP-ELEC-12',
    origin: 'Dharamshala ISBT',
    destination: 'McLeod Ganj',
    route_category: 'Electric Buses',
    bus_type: 'HRTC Electric',
    is_volvo: false,
    is_ac: false,
    is_hrtc: true,
    is_local: true,
    departure_time: '07:00 (Every 30 Mins)',
    arrival_time: '07:35',
    operating_days: 'Daily',
    frequency: 'Every 30 Mins',
    daily_frequency_count: 24,
    fare: '₹30',
    depot: 'Dharamshala',
    district: 'Kangra',
    stops: [
      { name: 'Dharamshala ISBT', dep: '07:00' },
      { name: 'Kachheri', dep: '07:10' },
      { name: 'Forsyth Ganj', dep: '07:25' },
      { name: 'McLeod Ganj Bus Stand', arr: '07:35' }
    ],
    source: 'Dharamshala Electric Depot',
    source_url: 'HRTC Kangra Region',
    last_verified: '2026-09-18',
    verification_status: '✓ Verified'
  },
  {
    id: 'route-ord-2',
    operator_id: 'hrtc',
    operator_name: 'HRTC Express',
    service_number: 'HP-EXP-550',
    origin: 'Shimla ISBT (Tutikandi)',
    destination: 'Manali Bus Stand',
    route_category: 'Long-Distance Services',
    bus_type: 'HRTC Ordinary',
    is_volvo: false,
    is_ac: false,
    is_hrtc: true,
    is_local: false,
    departure_time: '07:30',
    arrival_time: '15:30',
    operating_days: 'Daily',
    frequency: '4 buses/day',
    daily_frequency_count: 4,
    fare: '₹490',
    depot: 'Shimla',
    district: 'Shimla',
    stops: [
      { name: 'Shimla ISBT', dep: '07:30' },
      { name: 'Shalaghat', dep: '08:45' },
      { name: 'Brahmaputra Bridge', dep: '09:40' },
      { name: 'Ghumarwin', dep: '10:30' },
      { name: 'Mandi ISBT', dep: '12:15' },
      { name: 'Pandoh', dep: '13:00' },
      { name: 'Kullu ISBT', dep: '14:20' },
      { name: 'Manali Bus Stand', arr: '15:30' }
    ],
    source: 'Official HRTC Depot Chart',
    source_url: 'https://hrtchp.com',
    last_verified: '2026-09-10',
    verification_status: '✓ Verified'
  },
  {
    id: 'route-ord-3',
    operator_id: 'hrtc',
    operator_name: 'HRTC Baijnath Depot',
    service_number: 'HP-ORD-202',
    origin: 'Baijnath',
    destination: 'Pathankot ISBT',
    route_category: 'Ordinary Buses',
    bus_type: 'HRTC Ordinary',
    is_volvo: false,
    is_ac: false,
    is_hrtc: true,
    is_local: false,
    departure_time: '06:15',
    arrival_time: '10:45',
    operating_days: 'Daily',
    frequency: '6 buses/day',
    daily_frequency_count: 6,
    fare: '₹210',
    depot: 'Baijnath',
    district: 'Kangra',
    stops: [
      { name: 'Baijnath Bus Stand', dep: '06:15' },
      { name: 'Palampur', dep: '06:50' },
      { name: 'Maranda', dep: '07:05' },
      { name: 'Bhawarna', dep: '07:20' },
      { name: 'Nagrota', dep: '07:45' },
      { name: 'Shahpur', dep: '08:30' },
      { name: 'Nurpur', dep: '09:40' },
      { name: 'Pathankot ISBT', arr: '10:45' }
    ],
    source: 'Baijnath Bus Stand Enquiry',
    source_url: 'Public Depot Notice Board',
    last_verified: '2026-09-14',
    verification_status: '✓ Verified'
  },

  // --- PRIVATE OPERATORS ---
  {
    id: 'route-pvt-1',
    operator_id: 'rana-coach',
    operator_name: 'Rana Coach',
    service_number: 'RC-KANGRA-01',
    origin: 'Palampur',
    destination: 'Pathankot ISBT',
    route_category: 'Private Operators',
    bus_type: 'Private Ordinary',
    is_volvo: false,
    is_ac: false,
    is_hrtc: false,
    is_local: false,
    departure_time: '07:30',
    arrival_time: '10:45',
    operating_days: 'Daily',
    frequency: 'Daily',
    daily_frequency_count: 2,
    fare: '₹220',
    depot: 'Palampur (Private)',
    district: 'Kangra',
    stops: [
      { name: 'Palampur Bus Stand', dep: '07:30' },
      { name: 'Bhawarna', dep: '07:50' },
      { name: 'Nagrota Bagwan', dep: '08:15' },
      { name: 'Shahpur', dep: '09:00' },
      { name: 'Nurpur', dep: '09:50' },
      { name: 'Pathankot ISBT', arr: '10:45' }
    ],
    source: 'Rana Coach Official Ticket Window',
    source_url: 'Private Operator Timetable',
    last_verified: '2026-09-16',
    verification_status: '✓ Verified'
  },
  {
    id: 'route-pvt-2',
    operator_id: 'new-walia',
    operator_name: 'New Walia Bus Service',
    service_number: 'NW-DHA-05',
    origin: 'Dharamshala ISBT',
    destination: 'Pathankot ISBT',
    route_category: 'Private Operators',
    bus_type: 'Private Ordinary',
    is_volvo: false,
    is_ac: false,
    is_hrtc: false,
    is_local: false,
    departure_time: '08:45',
    arrival_time: '11:30',
    operating_days: 'Daily',
    frequency: '2 buses/day',
    daily_frequency_count: 2,
    fare: '₹180',
    depot: 'Dharamshala',
    district: 'Kangra',
    stops: [
      { name: 'Dharamshala ISBT', dep: '08:45' },
      { name: 'Gaggal', dep: '09:05' },
      { name: 'Shahpur', dep: '09:35' },
      { name: 'Jassur', dep: '10:40' },
      { name: 'Pathankot ISBT', arr: '11:30' }
    ],
    source: 'Verified Operator Submission',
    source_url: 'Dharamshala Private Union',
    last_verified: '2026-09-12',
    verification_status: '✓ Verified'
  },
  {
    id: 'route-pvt-3',
    operator_id: 'shivam-deluxe',
    operator_name: 'Shivam Luxury Travel',
    service_number: 'SL-MALI-88',
    origin: 'Manali',
    destination: 'Delhi ISBT Kashmiri Gate',
    route_category: 'Private Operators',
    bus_type: 'Private AC Volvo',
    is_volvo: true,
    is_ac: true,
    is_hrtc: false,
    is_local: false,
    departure_time: '17:30',
    arrival_time: '06:45 (Next Day)',
    operating_days: 'Daily',
    frequency: '1 service/day',
    daily_frequency_count: 1,
    fare: '₹1,250',
    depot: 'Manali Private Stand',
    district: 'Kullu',
    stops: [
      { name: 'Manali Private Volvo Stand', dep: '17:30' },
      { name: 'Kullu Bypass', dep: '18:40' },
      { name: 'Mandi Bypass', dep: '20:30' },
      { name: 'Chandigarh Bypass', dep: '02:00' },
      { name: 'Delhi ISBT Kashmiri Gate', arr: '06:45' }
    ],
    source: 'RedBus Partner Verification',
    source_url: 'https://redbus.in',
    last_verified: '2026-09-19',
    verification_status: '✓ Verified'
  },

  // --- RURAL & LOCAL VILLAGE ROUTES (1-3 BUSES/DAY) ---
  {
    id: 'route-local-1',
    operator_id: 'rana-coach',
    operator_name: 'Rana Coach Local Service',
    service_number: 'RC-VILL-09',
    origin: 'Chachian Village',
    destination: 'Palampur Hospital & Market',
    route_category: 'Local Bus Routes',
    bus_type: 'Local Village Bus',
    is_volvo: false,
    is_ac: false,
    is_hrtc: false,
    is_local: true,
    departure_time: '08:15 AM & 02:30 PM',
    arrival_time: '08:50 AM & 03:05 PM',
    operating_days: 'Daily except Sunday',
    frequency: '2 buses/day',
    daily_frequency_count: 2,
    fare: '₹25',
    depot: 'Palampur Rural',
    district: 'Kangra',
    stops: [
      { name: 'Chachian Village Bus Stop', dep: '08:15 AM' },
      { name: 'Tangra Gaon', dep: '08:25 AM' },
      { name: 'Chowki Village', dep: '08:35 AM' },
      { name: 'Civil Hospital Palampur', dep: '08:45 AM' },
      { name: 'Palampur Main Market Bus Stand', arr: '08:50 AM' }
    ],
    source: 'Local Panchayat Notice & Passengers',
    source_url: 'Panchayat Verification',
    last_verified: '2026-09-18',
    verification_status: '✓ Verified',
    rural_notice: 'This route operates only 2–3 times per day.'
  },
  {
    id: 'route-local-2',
    operator_id: 'lucky-bus',
    operator_name: 'Lucky Local Express',
    service_number: 'LB-MND-03',
    origin: 'Tihra Remote Village',
    destination: 'Mandi Zonal Hospital & Bus Stand',
    route_category: 'Local Bus Routes',
    bus_type: 'Local Village Bus',
    is_volvo: false,
    is_ac: false,
    is_hrtc: false,
    is_local: true,
    departure_time: '07:00 AM & 04:00 PM',
    arrival_time: '08:20 AM & 05:20 PM',
    operating_days: 'Daily',
    frequency: '2 buses/day',
    daily_frequency_count: 2,
    fare: '₹50',
    depot: 'Mandi Rural',
    district: 'Mandi',
    stops: [
      { name: 'Tihra Village Chowk', dep: '07:00 AM' },
      { name: 'Dharampur Bazar', dep: '07:30 AM' },
      { name: 'Kotli Village', dep: '07:55 AM' },
      { name: 'Mandi Zonal Hospital', dep: '08:15 AM' },
      { name: 'Mandi ISBT', arr: '08:20 AM' }
    ],
    source: 'Mandi Private Bus Operators Union',
    source_url: 'Local Timetable Board',
    last_verified: '2026-09-15',
    verification_status: '✓ Verified',
    rural_notice: 'This route operates only 2–3 times per day.'
  },
  {
    id: 'route-local-3',
    operator_id: 'hrtc',
    operator_name: 'HRTC Tribal Local Service',
    service_number: 'HP-PEO-01',
    origin: 'Chhitkul Village (Kinnaur)',
    destination: 'Reckong Peo Bus Stand',
    route_category: 'Local Bus Routes',
    bus_type: 'HRTC Ordinary',
    is_volvo: false,
    is_ac: false,
    is_hrtc: true,
    is_local: true,
    departure_time: '06:00 AM & 01:30 PM',
    arrival_time: '08:30 AM & 04:00 PM',
    operating_days: 'Daily (Subject to Weather)',
    frequency: '2 buses/day',
    daily_frequency_count: 2,
    fare: '₹95',
    depot: 'Reckong Peo',
    district: 'Kinnaur',
    stops: [
      { name: 'Chhitkul Village', dep: '06:00 AM' },
      { name: 'Rakcham', dep: '06:25 AM' },
      { name: 'Sangla Bazar', dep: '07:00 AM' },
      { name: 'Karcham Dam', dep: '07:45 AM' },
      { name: 'Powari', dep: '08:10 AM' },
      { name: 'Reckong Peo ISBT', arr: '08:30 AM' }
    ],
    source: 'Reckong Peo HRTC Enquiry',
    source_url: 'Kinnaur District Administration',
    last_verified: '2026-09-14',
    verification_status: '✓ Verified',
    rural_notice: 'This route operates only 2–3 times per day.'
  },
  {
    id: 'route-local-4',
    operator_id: 'hrtc',
    operator_name: 'HRTC Bharmour Shuttle',
    service_number: 'HP-CHA-14',
    origin: 'Hadsar Village (Manimahesh Base)',
    destination: 'Chamba ISBT',
    route_category: 'Local Bus Routes',
    bus_type: 'HRTC Ordinary',
    is_volvo: false,
    is_ac: false,
    is_hrtc: true,
    is_local: true,
    departure_time: '07:30 AM',
    arrival_time: '10:45 AM',
    operating_days: 'Daily',
    frequency: '1 bus/day',
    daily_frequency_count: 1,
    fare: '₹140',
    depot: 'Chamba',
    district: 'Chamba',
    stops: [
      { name: 'Hadsar Village', dep: '07:30 AM' },
      { name: 'Bharmour Market', dep: '08:15 AM' },
      { name: 'Kharamukh', dep: '09:00 AM' },
      { name: 'Luna Village', dep: '09:30 AM' },
      { name: 'Chamba ISBT', arr: '10:45 AM' }
    ],
    source: 'Chamba Depot Timeboard',
    source_url: 'Chamba Transport Union',
    last_verified: '2026-09-11',
    verification_status: '✓ Verified',
    rural_notice: 'This route operates only 2–3 times per day.'
  },
  {
    id: 'route-local-5',
    operator_id: 'kajal-bus',
    operator_name: 'Kajal Rural Express',
    service_number: 'KB-KNG-08',
    origin: 'Baroh Village',
    destination: 'Kangra Railway Station & ISBT',
    route_category: 'Local Bus Routes',
    bus_type: 'Local Village Bus',
    is_volvo: false,
    is_ac: false,
    is_hrtc: false,
    is_local: true,
    departure_time: '07:15 AM, 11:30 AM & 03:45 PM',
    arrival_time: '08:10 AM, 12:25 PM & 04:40 PM',
    operating_days: 'Daily',
    frequency: '3 buses/day',
    daily_frequency_count: 3,
    fare: '₹40',
    depot: 'Kangra Rural',
    district: 'Kangra',
    stops: [
      { name: 'Baroh Village Square', dep: '07:15 AM' },
      { name: 'Drombla Village', dep: '07:30 AM' },
      { name: 'Zamanabad', dep: '07:45 AM' },
      { name: 'Kangra Fort', dep: '07:55 AM' },
      { name: 'Kangra Bus Stand', arr: '08:10 AM' }
    ],
    source: 'Verified Local Conductor Logbook',
    source_url: 'Field Verification',
    last_verified: '2026-09-19',
    verification_status: '✓ Verified',
    rural_notice: 'This route operates only 2–3 times per day.'
  }
];

export const INITIAL_SUBMISSIONS = [
  {
    id: 'sub-101',
    submitted_by: 'Vikas Sharma (Palampur Resident)',
    operator_name: 'New Rana Travel Lines',
    headquarters: 'Bhawarna, Kangra',
    district: 'Kangra',
    contact: '+91 98165-88220',
    website: 'N/A',
    origin: 'Baijnath',
    destination: 'Chandigarh ISBT 43',
    bus_type: 'Private Luxury Bus',
    is_volvo: false,
    is_ac: true,
    is_local: false,
    departure_time: '06:00 AM',
    arrival_time: '12:30 PM',
    operating_days: 'Daily',
    photos: 'https://images.unsplash.com/photo-1544620347-c4fd4a3d5957?w=600',
    additional_info: 'Runs daily morning semi-deluxe service with pushback seats.',
    source: 'Physical Conductor Card',
    status: 'Pending Verification',
    date: '2026-09-18'
  },
  {
    id: 'sub-102',
    submitted_by: 'Pooja Thakur (Solan)',
    operator_name: 'Himalayan Express Lines',
    headquarters: 'Solan, HP',
    district: 'Solan',
    contact: '+91 94182-33100',
    website: 'N/A',
    origin: 'Kasauli',
    destination: 'Chandigarh ISBT 17',
    bus_type: 'Local Village Bus',
    is_volvo: false,
    is_ac: false,
    is_local: true,
    departure_time: '08:00 AM & 02:00 PM',
    arrival_time: '09:45 AM & 03:45 PM',
    operating_days: 'Daily',
    photos: 'N/A',
    additional_info: 'Rural route for morning commuters & students.',
    source: 'Kasauli Bus Stop Timetable',
    status: 'Pending Verification',
    date: '2026-09-19'
  }
];

export const INITIAL_REPORTS = [
  {
    id: 'rep-201',
    route_id: 'route-ord-1',
    route_name: 'HRTC Ordinary: Palampur → Chandigarh',
    issue_type: 'Wrong Timing',
    description: 'Morning 05:30 AM bus now leaves at 05:45 AM due to highway roadworks.',
    submitted_by: 'Anil Kumar',
    contact: 'anil.k@gmail.com',
    status: 'Open',
    date: '2026-09-19'
  }
];
